version: '3.9'

services:
  iframe-test:
    build: .
    image: iframe-test:latest
    container_name: iframe-test
    ports:
      - '8888:80'
    networks:
      - jc21-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  jc21-network:
    external: true
    name: avatar-mgmt-jc21-network
